{% set name = "qcportal" %}
{% set version = "0.6.0" %}
{% set sha256 = "b6b07d241d8fe0ef325841b8e2e8a07d06b40a6c0a112d1b8cad1e9c23f878fd" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.6
    - pip

  run:
    - python >=3.6
    - numpy
    - pandas
    - requests
    - pyyaml
    - pydantic >=0.20
    - qcelemental >=0.3.3
    - plotly

test:
  requires:
    - pytest
  imports:
    - qcportal
  commands:
    - pytest --pyargs qcportal

about:
  home: https://github.com/MolSSI/QCPortal
  dev_url: https://github.com/MolSSI/QCPortal
  doc_url: https://qcfractal.readthedocs.io/en/latest/
  doc_source_url: https://github.com/MolSSI/QCFractal/blob/master/docs/source/portal-client.rst
  license: BSD-3-Clause
  license_url: https://opensource.org/licenses/BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: A client interface to the QC Archive Project

extra:
    recipe-maintainers:
        - dgasmith
        - lnaden
